### ISSUE TITLE
API Change to python-consul

### ISSUE THREAD

**Issue by cablehead** [ClearcodeHQ/ianitor#10]
Hi!

I just pushed version v0.4.0 of python-consul which deprecates the api for how checks have been registered.

```python
import consul

c = consul.Consul()
c.agent.service.register('foo', script='/bin/check', interval='10s')
```

Has changed to:

```python
import consul

Check = consul.Check

c = consul.Consul()
c.agent.service.register('foo', check=Check.script('/bin/check', '10s'))
```

Registering the old way now logs a warning that that api has been deprecated.

Apologies for the inconvenience. And let me know if you've any concerns with the new api!

**Comment by swistakm** [comment]
Thanks for information. Thanks to @mruwnik we have now requirements fixed to `python-consul==0.4.0` and also [a new release](https://github.com/ClearcodeHQ/ianitor/releases/tag/0.0.4).

I've seen now that ianitor is mentioned in tools section of python-consul documentation. Thanks for that!
