### ISSUE TITLE
What have just happened?

### ISSUE THREAD

**Issue by swistakm** [ClearcodeHQ/ianitor#15]
I have been just removed from ClearcodeHQ organization. I know I don't work at CC anymore but IIRC we had gentelman's agreement that I stay here to maintain this repository and do not mess with other code.

What have changed? We are not gentelmen anymore? Now its kind of stalemate. I don't have access to the official repository but I am the only maintainer of this package on PyPI.

**Comment by trojkat** [comment]
I'll check that.

**Comment by fizyk** [comment]
@swistakm please check, I'll investigate further. You've been given permission to this repo, just to make sure your organisational status won't affect your access here.
